# Generated by Django 6.0.1 on 2026-01-08 02:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyResearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('industry', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('overview', models.TextField(blank=True)),
                ('stock_ticker', models.CharField(blank=True, max_length=20)),
                ('stock_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('stock_change_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('stock_change_1w', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('stock_change_1m', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('market_cap', models.CharField(blank=True, max_length=50)),
                ('stock_history', models.TextField(blank=True)),
                ('recent_developments', models.TextField(blank=True)),
                ('overall_sentiment', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True)),
                ('sentiment_label', models.CharField(blank=True, max_length=20)),
                ('positive_count', models.IntegerField(default=0)),
                ('negative_count', models.IntegerField(default=0)),
                ('neutral_count', models.IntegerField(default=0)),
                ('llm_summary', models.TextField(blank=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Company researches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500)),
                ('title', models.CharField(max_length=500)),
                ('source', models.CharField(max_length=200)),
                ('source_name', models.CharField(blank=True, max_length=200)),
                ('author', models.CharField(blank=True, max_length=200)),
                ('published_date', models.CharField(blank=True, max_length=50)),
                ('content_preview', models.TextField(blank=True)),
                ('word_count', models.IntegerField(default=0)),
                ('source_type', models.CharField(blank=True, max_length=50)),
                ('credibility_score', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('credibility_note', models.CharField(blank=True, max_length=300)),
                ('relevance_score', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('finbert_score', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True)),
                ('vader_score', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True)),
                ('textblob_polarity', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True)),
                ('textblob_subjectivity', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True)),
                ('roberta_score', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True)),
                ('llm_score', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True)),
                ('llm_commentary', models.TextField(blank=True)),
                ('ensemble_score', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True)),
                ('model_agreement', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('sentiment_label', models.CharField(blank=True, max_length=20)),
                ('research', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='research.companyresearch')),
            ],
            options={
                'ordering': ['-ensemble_score'],
            },
        ),
    ]
