# Generated by Django 6.0.1 on 2026-01-08 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyresearch',
            name='progress_message',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
