# Generated by Django 6.0.1 on 2026-01-08 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0002_companyresearch_progress_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='textblob_polarity',
        ),
        migrations.RemoveField(
            model_name='article',
            name='textblob_subjectivity',
        ),
    ]
