# Generated by Django 6.0.1 on 2026-01-12 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0003_remove_textblob_fields'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='llm_commentary',
            new_name='llm_reasoning',
        ),
        migrations.RemoveField(
            model_name='article',
            name='roberta_score',
        ),
        migrations.RemoveField(
            model_name='article',
            name='vader_score',
        ),
    ]
