# Generated by Django 6.0.1 on 2026-01-12 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0004_remove_vader_roberta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='credibility_note',
        ),
        migrations.RemoveField(
            model_name='article',
            name='credibility_score',
        ),
        migrations.RemoveField(
            model_name='article',
            name='relevance_score',
        ),
        migrations.RemoveField(
            model_name='article',
            name='source_type',
        ),
    ]
